CREATE TABLE IF NOT EXISTS worker (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH (NAME) > 2),
    BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900),
    LEVEL VARCHAR(128) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT NOT NULL CHECK (SALARY > 100 AND SALARY < 100000)
);

CREATE TABLE IF NOT EXISTS client (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH (NAME) > 2)
);

CREATE TABLE IF NOT EXISTS project (
    ID BIGSERIAL PRIMARY KEY,
    CLIENT_ID BIGINT,
    START_DATE DATE,
    FINISH_DATE DATE,
    CONSTRAINT check_date_range 
        CHECK (FINISH_DATE >= START_DATE + INTERVAL '1 month' AND FINISH_DATE <= START_DATE + INTERVAL '100 months'),
    CONSTRAINT fk_client_id
        FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
);

CREATE TABLE IF NOT EXISTS project_worker (
    PROJECT_ID BIGINT,
    WORKER_ID BIGINT,
    CONSTRAINT fk_project_id
        FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    CONSTRAINT fk_worker_id
        FOREIGN KEY (WORKER_ID) REFERENCES worker(ID),
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
);