SELECT
    p.ID AS NAME,
    EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) * SUM(w.SALARY) AS PRICE
 FROM project p
 LEFT JOIN project_worker pw ON p.ID = pw.PROJECT_ID
 LEFT JOIN worker w ON pw.WORKER_ID = w.ID
 GROUP BY p.ID
 ORDER BY PRICE DESC;